### ISSUE TITLE
Roxygen generator clarification

### ISSUE THREAD

**Issue by SurajGupta** [karthik/Rtools#10]
According to the doucmentation: "...select first line of a function till the first {, press keybinding and it will generate a template with @params from the function definition..."

which keybinding?  Could you make it more clear exactly what is required to get this to work?

**Comment by karthik** [comment]
They keybinding is in this associated keymap file (https://github.com/karthikram/Rtools/blob/master/Default%20(OSX).sublime-keymap).  For OSX, the default keybinding is `Command + Alt + Shift + R` and although I have never tried this on Windows, the comparable keybinding should be `Windows + Alt + Shift + R`. However, you can customize this to whatever you'd like by copying the `r_docs` binding from https://github.com/karthikram/Rtools/blob/master/Default%20(OSX).sublime-keymap#L3 into your own keybindings file (Preferences > Key bindings - User).

**Comment by SurajGupta** [comment]
very cool!  worked like a charm.
