### ISSUE TITLE
RTools for ST3

### ISSUE THREAD

**Issue by GregoryEady** [karthik/Rtools#18]
I just upgraded to ST3, but unfortunately, RTools doesn't seem to send R code to the R (3.0.0) window as it does in ST2. I wonder if there's a quick workaround for this.

**Comment by karthik** [comment]
Thanks for opening this issue. I haven't upgraded to ST3 yet so I don't know how much work is involved. I'll leave this open in case anyone wants to submit a pull request before I get around to it.

**Comment by jlegewie** [comment]
It should be pretty easy to fix this. Eady, can you post the error message from the console here and try to run python 2to3 on the py file?

**Comment by GregoryEady** [comment]
There actually is no error message. I hit cmd-enter from ST2, and the R code is executed in the R window. When I do the same in ST3 (having gone through the same installation procedure), nothing happens.

Note: with R 3.0.0, one has to change the appropriate text in rtools.py from "R64" to "R" because there are no longer separate R64 and R, but that worked fine when I did that in ST2.

**Comment by karthik** [comment]
> Note: with R 3.0.0, one has to change the appropriate text in rtools.py from "R64" to "R" because there are no longer separate R64 and R, but that worked fine when I did that in ST2.

Right. I didn't want to change it because I don't want it to break for anyone who hasn't upgraded. It's a simple edit that people can do locally.

**Comment by GregoryEady** [comment]
I tried 2to3, but it didn't seem to change anything.

This is the error:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 531, in run_
    return self.run(edit)
  File "/Users/nameeady/Library/Application Support/Sublime Text 3/Packages/Rtools/Rtools.py", line 35, in run
    filescope = self.view.syntax_name(self.view.sel()[0].b)
AttributeError: 'View' object has no attribute 'syntax_name'

**Comment by sdaza** [comment]
Any news about a workaround to use RTools in ST3?

**Comment by persquare** [comment]
'syntax_name' in ST2 became 'scope_name' in ST3

**Comment by karthik** [comment]
I moved development over here: https://github.com/karthik/Rtools3

roxygen documentation works now. Thanks @persquare 
Will update sending text to R/terminal/RStudio
