### ISSUE TITLE
Allow communicating with other R sessions

### ISSUE THREAD

**Issue by wch** [karthik/Rtools#4]
I usually use R from the terminal, and run multiple sessions at once. It would be nice to be able to:
- "Connect" an ST window to any given instance of R. This could be done by finding the process id of an R instance with `Sys.getpid()`, and somehow give the ST Rtools plugin that pid.
- Set a default R process that ST sends commands to. This is the R process that ST sends commands to, unless otherwise specified. The default default could be the R instance with the lowest-numbered pid.  It should also be possible to change the default.

**Comment by jlegewie** [comment]
It does not really address your suggestions but might still be helpful:
I am often running R on my local machine and in the cloud using iTerm, which is just an enhanced terminal. 

Here is the python script to send code from ST2 to iTerm:
https://gist.github.com/2345210

I bind this function to another key-combination. Note that you can send any code to iTerm using this script (not only R).

**Comment by wch** [comment]
That's cool - I adapted your gist to work with Terminal.app. It only sends it to the top Terminal though -- it doesn't "attach" a ST view to a particular terminal.
https://gist.github.com/2353376

It would be nice to be able to configure the desired output (R64, R, iTerm, Terminal, etc) like other ST2 things, with a JSON config file.

**Comment by wch** [comment]
Come to think of it, sending it to terminal or iterm isn't really an R thing -- this would be useful for any language. Maybe it's a better fit with https://github.com/wbond/sublime_terminal.

**Comment by jlegewie** [comment]
Yes, I agree. Personally, I am actually using a class SendSelection, which uses the language definition to termini whether code should be send to R, or Stata and anything else goes to the terminal. A second key combo sends all code to the terminal. But all this could be set with preference files.

I am currently working on another ST2 plugin and might upload the full send-selection code another time.

**Comment by ChrisKlijn** [comment]
This works really well for me:

https://github.com/wch/SendText

**Comment by wch** [comment]
Funny - I filed this issue and then later made the SendText plugin, basing it off of the Rtools code. :)

**Comment by ChrisKlijn** [comment]
Hah, sorry for the confusion, I was quickly browsing and perhaps over-enthusiastically replied here.
